function drawBin(x, y)

    hold on;

    % Main bin
    rectangle("Position", [x-8 y-5 16 10], ...
              "FaceColor", [0.7 0.7 0.7], ...
              "EdgeColor", [0.3 0.3 0.3], ...
              "LineWidth", 2);

    % Bin lid
    rectangle("Position", [x-9 y+5 18 2], ...
              "FaceColor", [0.5 0.5 0.5], ...
              "EdgeColor", [0.25 0.25 0.25], ...
              "LineWidth", 2);

    % Vertical lines on the bin
    line([x-4 x-4], [y-3 y+4], ...
         "LineWidth", 1.2);

    line([x x], [y-3 y+4], ...
         "LineWidth", 1.2);

    line([x+4 x+4], [y-3 y+4], ...
         "LineWidth", 1.2);

endfunction
