function drawbrain(x, y)

    hold on;

    % =========================
    % BRAIN OUTLINE
    % =========================

    brain_x = [ ...
        x-7, x-8, x-7, x-5, x-4, x-2, x, ...
        x+2, x+4, x+6, x+8, x+8, x+7, ...
        x+5, x+4, x+2, x, x-2, x-4, x-6 ...
    ];

    brain_y = [ ...
        y, y+2, y+4, y+5.5, y+6, y+6.5, y+6.2, ...
        y+6.5, y+6, y+5.5, y+4, y+2, y, ...
        y-2, y-3.5, y-4, y-4.5, y-4, y-3.5, y-2 ...
    ];

    fill(brain_x, brain_y, [1 0.65 0.75], ...
         "EdgeColor", [0.7 0.2 0.4], ...
         "LineWidth", 2);


    % =========================
    % CENTRAL FISSURE
    % =========================

    line([x x], ...
         [y-3.5 y+5.5], ...
         "LineWidth", 2);


    % =========================
    % BRAIN GROOVES
    % =========================

    % Left hemisphere
    line([x-6 x-4 x-5], ...
         [y+4.5 y+3.5 y+2], ...
         "LineWidth", 1.2);

    line([x-4 x-2 x-3], ...
         [y+5.5 y+4.5 y+3], ...
         "LineWidth", 1.2);

    line([x-6 x-4 x-5], ...
         [y+1 y y-1], ...
         "LineWidth", 1.2);

    line([x-4 x-2 x-3], ...
         [y-1 y-2 y-3], ...
         "LineWidth", 1.2);


    % Right hemisphere
    line([x+6 x+4 x+5], ...
         [y+4.5 y+3.5 y+2], ...
         "LineWidth", 1.2);

    line([x+4 x+2 x+3], ...
         [y+5.5 y+4.5 y+3], ...
         "LineWidth", 1.2);

    line([x+6 x+4 x+5], ...
         [y+1 y y-1], ...
         "LineWidth", 1.2);

    line([x+4 x+2 x+3], ...
         [y-1 y-2 y-3], ...
         "LineWidth", 1.2);

endfunction
