function h_all = drawneuron(x, y, type)
 % Draw a neuron at position (x,y) and return a vector of all graphic handles
 % type = 1 -> healthy neuron
 % type = 2 -> degenerated neuron

 hold on;
 h_all = []; % Array to store all handles created for this neuron

 % =========================
% HEALTHY NEURON
% =========================
if type == 1

    % Cell body
    h_all(end+1) = plot(x, y, "o", ...
        "MarkerSize", 11, ...
        "MarkerFaceColor", [0.6 0.8 1], ...
        "MarkerEdgeColor", [0.1 0.3 0.8], ...
        "LineWidth", 2);

    % Nucleus
    h_all(end+1) = plot(x, y, "o", ...
        "MarkerSize", 3, ...
        "MarkerFaceColor", [0.9 0.95 1], ...
        "MarkerEdgeColor", [0.2 0.4 0.8]);


    % =========================
    % DENDRITES
    % =========================

    % ---------- Upper-left dendritic tree ----------

    h_all(end+1) = line([x-1.5 x-2.2 x-2.9], ...
                        [y+0.5 y+1.2 y+1.8], ...
                        "LineWidth", 1.3);

    h_all(end+1) = line([x-2.2 x-2.7], ...
                        [y+1.2 y+1.8], ...
                        "LineWidth", 1.0);

    h_all(end+1) = line([x-2.9 x-3.4], ...
                        [y+1.8 y+2.0], ...
                        "LineWidth", 0.9);


    % ---------- Upper-right dendritic tree ----------

    h_all(end+1) = line([x+1.4 x+2.3 x+3.2], ...
                        [y+0.5 y+1.9 y+3.0], ...
                        "LineWidth", 1.3);

    h_all(end+1) = line([x+2.3 x+3.5], ...
                        [y+1.9 y+2.2], ...
                        "LineWidth", 1.0);

    h_all(end+1) = line([x+3.2 x+3.8], ...
                        [y+3.0 y+3.8], ...
                        "LineWidth", 0.9);


    % ---------- Left dendritic tree ----------

    h_all(end+1) = line([x-1.6 x-2.4 x-2.9], ...
                        [y+0.1 y+0.3 y+0.8], ...
                        "LineWidth", 1.3);

    % Branch 1
    h_all(end+1) = line([x-2.4 x-2.9], ...
                        [y+0.3 y-0.2], ...
                        "LineWidth", 1.0);


    % ---------- Right dendritic tree ----------

    h_all(end+1) = line([x+1.9 x+3.0 x+4.4], ...
                        [y+0.1 y+0.5 y+1.2], ...
                        "LineWidth", 1.3);

    % Branch 1
    h_all(end+1) = line([x+3.0 x+4.1], ...
                        [y+0.5 y-0.3], ...
                        "LineWidth", 1.1);

    % Branch 2
    h_all(end+1) = line([x+4.4 x+5.5], ...
                        [y+1.2 y+1.9], ...
                        "LineWidth", 1.1);

    % Branch 3
    h_all(end+1) = line([x+4.4 x+5.2], ...
                        [y+1.2 y+0.5], ...
                        "LineWidth", 1.0);


    % ---------- Lower-left dendritic tree ----------

    h_all(end+1) = line([x-1.7 x-2.2 x-2.8], ...
                        [y-0.7 y-1.2 y-1.8], ...
                        "LineWidth", 1.3);

    % Branch 1
    h_all(end+1) = line([x-2.2 x-2.8], ...
                        [y-1.2 y-1.7], ...
                        "LineWidth", 1.0);


    % ---------- Lower-right dendritic tree ----------

    h_all(end+1) = line([x+1.8 x+2.4 x+3.5], ...
                        [y-0.8 y-1.9 y-3.1], ...
                        "LineWidth", 1.3);

    % Branch 1
    h_all(end+1) = line([x+2.4 x+3.5], ...
                        [y-1.9 y-2.5], ...
                        "LineWidth", 1.1);

    % Branch 2
    h_all(end+1) = line([x+3.5 x+4.5], ...
                        [y-3.1 y-3.8], ...
                        "LineWidth", 1.0);


    % =========================
    % AXONS
    % =========================

    % Main axon going to the right
    h_all(end+1) = line([x+1.5 x+1.5 x+2.5 x+3.7], ...
                        [y-0.5 y-0.9 y-1.1 y-1.4], ...
                        "LineWidth", 2);

    h_all(end+1) = line([x+3.7 x+4.5], ...
                        [y-1.4 y-0.9], ...
                        "LineWidth", 1.2);

    h_all(end+1) = line([x+3.7 x+4.6], ...
                        [y-1.4 y-1.9], ...
                        "LineWidth", 1.2);

    h_all(end+1) = line([x+4.5 x+5.1], ...
                        [y-0.9 y-0.6], ...
                        "LineWidth", 1.0);

    h_all(end+1) = line([x+4.6 x+5.2], ...
                        [y-1.9 y-2.2], ...
                        "LineWidth", 1.0);


   % Small downward axon from the soma
h_all(end+1) = line([x x], ...
                    [y-2.1 y-3.5], ...
                    "LineWidth", 1.8);


else

    % =========================
    % DEGENERATED NEURON
    % =========================

    % Cell body
    h_all(end+1) = plot(x, y, "o", ...
        "MarkerSize", 11, ...
        "MarkerFaceColor", [0.88 0.92 0.93], ...
        "MarkerEdgeColor", [0.55 0.62 0.64], ...
        "LineWidth", 1.5);

    % Nucleus
    h_all(end+1) = plot(x, y, "o", ...
        "MarkerSize", 2, ...
        "MarkerFaceColor", [0.75 0.80 0.81], ...
        "MarkerEdgeColor", [0.50 0.55 0.56]);


    % =========================
    % DAMAGED DENDRITES
    % =========================

   % ---------- Short upper-left damaged dendrite ----------

h_all(end+1) = line([x-1.4 x-2.3 x-3.1], ...
                    [y+0.8 y+1.5 y+1.8], ...
                    "LineWidth", 1.1, ...
                    "Color", [0.65 0.72 0.73]);
% Short branch
h_all(end+1) = line([x-1.4 x-1.7 x-2.1], ...
                    [y+1.3 y+1.5 y+2.8], ...
                    "LineWidth", 1.1, ...
                    "Color", [0.65 0.72 0.73]);

    % ---------- Upper-right damaged dendrite ----------

    h_all(end+1) = line([x+1.6 x+3.1 x+4.3], ...
                        [y+0.8 y+2.1 y+3.1], ...
                        "LineWidth", 1.1, ...
                        "Color", [0.65 0.72 0.73]);

   % Short branch
h_all(end+1) = line([x+2.6, x+3], ...
                    [y+2.1, y+2.7], ...
                    "LineWidth", 0.9, ...
                    "Color", [0.65 0.72 0.73]);



    % ---------- Right damaged dendrite ----------

h_all(end+1) = line([x+1.6, x+3, x+3.4], ...
                    [y+0.4, y+0.8, y+1.1], ...
                    "LineWidth", 1.1, ...
                    "Color", [0.65 0.72 0.73]);

    % Short branch
    h_all(end+1) = line([x+3.2 x+4.2], ...
                        [y+0.4 y-0.4], ...
                        "LineWidth", 0.9, ...
                        "Color", [0.65 0.72 0.73]);


    % ---------- Lower-right damaged dendrite ----------

    h_all(end+1) = line([x+1.6 x+2.8 x+3.8], ...
                        [y-0.8 y-1.9 y-2.8], ...
                        "LineWidth", 1.1, ...
                        "Color", [0.65 0.72 0.73]);

endif
endfunction
