function graphics()

    fig = figure('Name', 'Save The Brain - Game', ...
                 'Position', [200, 100, 800, 600], ...
                 'Color', [0.97 0.97 0.98]);

    axes('Position', [0 0 1 1]);

    axis([0 100 0 100]);
    axis off;
    hold on;

    % =========================
    % HAND-DRAWN BACKGROUND
    % =========================

    bg = imread('background.jpg');

    image([0 100], [100 0], bg);

    hold on;

 % =========================
% TRASH ZONE
% =========================

rectangle('Position', [14, 11, 18, 20], ...
          'FaceColor', [0.95 0.92 0.92], ...
          'EdgeColor', [0.8 0.5 0.5], ...
          'LineWidth', 1.5, ...
          'Curvature', 0.1);

drawbin(23, 20);

text(23, 13, 'TRASH', ...
     'FontSize', 11, ...
     'FontWeight', 'bold', ...
     'HorizontalAlignment', 'center', ...
     'Color', [0.7 0.2 0.2], ...
     'FontName', 'Helvetica', ...
     'BackgroundColor', [0.95 0.92 0.92]);


% =========================
% BRAIN ZONE
% =========================

rectangle('Position', [68, 11, 18, 20], ...
          'FaceColor', [0.92 0.95 0.92], ...
          'EdgeColor', [0.5 0.8 0.5], ...
          'LineWidth', 1.5, ...
          'Curvature', 0.1);

drawbrain(77, 20);

text(77, 13, 'BRAIN', ...
     'FontSize', 11, ...
     'FontWeight', 'bold', ...
     'HorizontalAlignment', 'center', ...
     'Color', [0.2 0.6 0.2], ...
     'FontName', 'Helvetica', ...
     'BackgroundColor', [0.92 0.95 0.92]);

    % Top header information with solid background to prevent text antialiasing blur
    text(50, 91, 'SAVE THE BRAIN', 'FontSize', 22, 'FontWeight', 'bold', 'HorizontalAlignment', 'center', 'FontName', 'Helvetica', 'Color', [0.2 0.2 0.2], 'BackgroundColor', [0.97 0.97 0.98]);

    global h_lives_text h_time_text;
    h_lives_text = text(14, 85, 'LIVES: ♥ ♥ ♥', 'FontSize', 11, 'FontWeight', 'bold', 'FontName', 'Helvetica', 'Color', [0.8 0.1 0.1], 'BackgroundColor', [0.97 0.97 0.98]);
    h_time_text = text(86, 85, 'TIME: 60', 'FontSize', 11, 'FontWeight', 'bold', 'HorizontalAlignment', 'right', 'FontName', 'Helvetica', 'Color', [0.2 0.2 0.2], 'BackgroundColor', [0.97 0.97 0.98]);
end
