function intro_screen()

    % Create intro window
    fig = figure('Name', 'Save The Brain - Intro', ...
                 'Position', [200, 100, 800, 600], ...
                 'Color', [0.91 0.87 0.98]);

    axes('Position', [0 0 1 1]);
    axis([0 100 0 100]);
    axis off;
    hold on;
% =========================
% INTRO BACKGROUND IMAGE
% =========================

intro_bg = imread('intro.jpg');

image([0 100], [100 0], intro_bg);

hold on;

    % =========================
    % TITLE
    % =========================

    text(50, 78, 'SAVE THE BRAIN', ...
         'FontSize', 30, ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.1 0.1 0.1], ...
         'FontName', 'Britannic Bold');


    % =========================
    % HOW TO PLAY
    % =========================

    text(50, 65, 'HOW TO PLAY', ...
         'FontSize', 21, ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.25 0.25 0.25], ...
         'FontName', 'Britannic Bold');


    % Step 1
    text(50, 56, '1. Click on a falling neuron to select it.', ...
         'FontSize', 17, ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.2 0.2 0.2], ...
         'FontName', 'Britannic Bold');


    % Step 2
    text(50, 50, '2. Click the correct target to sort the neuron.', ...
         'FontSize', 17, ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.2 0.2 0.2], ...
         'FontName', 'Britannic Bold');


    % =========================
    % TARGETS
    % =========================

    text(50, 43, 'HEALTHY NEURON  →  BRAIN', ...
         'FontSize', 17, ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.1 0.55 0.2], ...
         'FontName', 'Britannic Bold');


    text(50, 37, 'DISEASED NEURON  →  TRASH', ...
         'FontSize', 17, ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.75 0.1 0.1], ...
         'FontName', 'Britannic Bold');


    % =========================
    % WARNING
    % =========================

    text(50, 31, 'Wrong target = lose a life!', ...
         'FontSize', 15, ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'Color', [0.75 0.1 0.1], ...
         'FontName', 'Britannic Bold');


    % =========================
    % START BUTTON
    % =========================

    uicontrol('Style', 'pushbutton', ...
              'String', 'START GAME', ...
              'Position', [300, 90, 200, 50], ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'FontName', 'Britannic Bold', ...
              'BackgroundColor', [0.2 0.7 0.2], ...
              'ForegroundColor', [1 1 1]);


    % =========================
    % WAIT FOR START
    % =========================

    set(findall(fig, 'Type', 'uicontrol'), ...
        'Callback', @(~,~) close_intro(fig));

    while ishghandle(fig)
        pause(0.1);
    end

end


% =========================
% CLOSE INTRO FUNCTION
% =========================

function close_intro(fig)

    if ishghandle(fig)
        close(fig);
    endif

end
